export enum RolesType {
    ADMIN = 'admin',
    USER = 'user',
    GUEST = 'guest',
}

export const ROLES_KEY = 'roles';

export enum Sort {
  ASC= 'ASC',
  DESC= 'DESC',
}

export enum StudentType {
  THI = 'thi',
  ON = 'ôn',
  ALL = 'ôn + thi',
}

export enum CityEnum {
  ANGIANG = 'An Giang',
  BARIAVUNGTAU = 'Bà Rịa – Vũng Tàu',
  BACLIEU = 'Bạc Liêu',
  BACGIANG = 'Bắc Giang',
  BACKAN = 'Bắc Kạn',
  BACNINH = 'Bắc Ninh',
  BENTRE = 'Bến Tre',
  BINHDUONG = 'Bình Dương',
  BINHDINH = 'Bình Định',
  BINHPHUOC = 'Bình Phước',
  BINHTHUAN = 'Bình Thuận',
  CAOBANG = 'Cao Bằng',
  CANTHO = 'Cần Thơ',
  CAMAU = 'Cà Mau',
  DAKNONG = 'Đắk Nông',
  DAKLAK = 'Đắk Lắk',
  DANANG = 'Đà Nẵng',
  DONGNAI = 'Đồng Nai',
  DONGTHAP = 'Đồng Tháp',
  DIENBIEN = 'Điện Biên',
  GIALAI = 'Gia Lai',
  HAGIANG = 'Hà Giang',
  HANOI = 'Hà Nội',
  HATINH = 'Hà Tĩnh',
  HANAM = 'Hà Nam',
  HAIDUONG = 'Hải Dương',
  HAIPHONG = 'Hải Phòng',
  HAUGIANG = 'Hậu Giang',
  HOABINH = 'Hòa Bình',
  TPHOCHIMINH = 'TP Hồ Chí Minh',
  HUNGYEN = 'Hưng Yên',
  KHANHHOA = 'Khánh Hòa',
  KIENGIANG = 'Kiên Giang',
  KONTUM = 'Kon Tum',
  LAICHAU = 'Lai Châu',
  LAOCAI = 'Lào Cai',
  LANGSON = 'Lạng Sơn',
  LAMDONG = 'Lâm Đồng',
  LONGAN = 'Long An',
  NAMDINH = 'Nam Định',
  NGHEAN = 'Nghệ An',
  NINHBINH = 'Ninh Bình',
  NINHTHUAN = 'Ninh Thuận',
  PHUTHO = 'Phú Thọ',
  PHUYEN = 'Phú Yên',
  QUANGBINH = 'Quảng Bình',
  QUANGNAM = 'Quảng Nam',
  QUANGNGAI = 'Quảng Ngãi',
  QUANGNINH = 'Quảng Ninh',
  QUANGTRI = 'Quảng Trị',
  SOCTRANG = 'Sóc Trăng',
  SONLA = 'Sơn La',
  TAYNINH = 'Tây Ninh',
  THAIBINH = 'Thái Bình',
  THAINGUYEN = 'Thái Nguyên',
  THANHHOA = 'Thanh Hóa',
  THUATHIENHUE = 'Thừa Thiên Huế',
  TIENGIANG = 'Tiền Giang',
  TRAVINH = 'Trà Vinh',
  TUYENQUANG = 'Tuyên Quang',
  VINHLONG = 'Vĩnh Long',
  VINHPHUC = 'Vĩnh Phúc',
  YENBAI = 'Yên Bái',
}

export enum EthnicEnum {
  KINH = 'Kinh',
  TAY = 'Tày',
  THAI = 'Thái',
  HOA = 'Hoa',
  KHO_ME = 'Khơ-me',
  MUONG = 'Mường',
  NUNG = 'Nùng',
  HMONG = 'HMông',
  DAO = 'Dao',
  GIA_RAI = 'Gia-rai',
  NGAI = 'Ngái',
  EDE = 'Ê-đê',
  BA_NA = 'Ba-na',
  XO_DANG = 'Xơ-Đăng',
  SAN_CHAY = 'Sán Chay',
  CO_HOI = 'Cơ-ho',
  CHAM = 'Chăm',
  SAN_DIU = 'Sán Dìu',
  HRE = 'Hrê',
  MNONG = 'Mnông',
  RA_GLAI = 'Ra-glai',
  XTIENG = 'Xtiêng',
  BRU_VAN_KIEU = 'Bru-Vân Kiều',
  THO = 'Thổ',
  GIAY = 'Giáy',
  GIE_TRIENG = 'Gié Triêng',
  MA = 'Mạ',
  KHO_MU = 'Khơ-mú',
  CO = 'Co',
  TA_OI = 'Tà-ôi',
  CHO_RO = 'Chơ-ro',
  KHANG = 'Kháng',
  XINH_MUN = 'Xinh-mun',
  HA_NHI = 'Hà Nhì',
  CHU_RU = 'Chu ru',
  LAO = 'Lào',
  LA_CHI = 'La Chí',
  LA_HA = 'La Ha',
  PHU_LA = 'Phù Lá',
  LA_HU = 'La Hủ',
  LU = 'Lự',
  LO_LO = 'Lô Lô',
  CHU = 'Chứt',
  MANG = 'Mảng',
  PA_THEN = 'Pà Thẻn',
  CO_LAO = 'Co Lao',
  CONG = 'Cống',
  BO_Y = 'Bố Y',
  SI_LA = 'Si La',
  PU_PEO = 'Pu Péo',
  BRAU = 'Brâu',
  O_DU = 'Ơ Đu',
  RO_MAM = 'Rơ măm',
}